# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed91da263acc4a8a47a7c8d0b4f16ad1111696023037144374bf692421fe7368785db1b2470e62b55b85b1be53837d871b99a9e59dfc320d099a7fe1f60e8e8c

test:
  secret_key_base: b206f9dae0f5ce68ec96639de1645260491e0ab103ba70c9bc4d397461814ccef0160a93068f6d8cd00716d140238750e8d7e166db36a6784c109e0f98bb68e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
